### PR TITLE
[#305] Smart Collect logic

### LINKED ISSUE #305: Smart Collect work
- stop indexer when pivot too high, but still run collector

### PR DESCRIPTION
**Pull request by WindowsVistaisCool**
Needs to test reverse indexing after hitting exit beambreak. May need to disable for Kettering if comms is a problem. Pivot angle check needs to be tested (may need to req pivot subsystem).

Closes #305

### CODE REVIEW

**Comment by HeeistHo** [comment]
wasn't there an issue with the shooter being too low?
you should probably have a minimum angle as well

otherwise i like the logic (but fix that linter smh)

**Comment by WindowsVistaisCool** [comment]
> wasn't there an issue with the shooter being too low? you should probably have a minimum angle as well
> 
> otherwise i like the logic (but fix that linter smh)

Possibly, but it could also be that we were running collector too fast. This logic slows it down once the note is half in the robot. We can add one if needed.

**Comment by MattD8957** [comment]
I say merge if this works and we can add additional things later as needed

**Review by MattD8957 — APPROVED** [review]
LGTM 👍

**Pull request merged**
