### PR TITLE
[#178] sing

### LINKED ISSUE #178: make it sing :D
this is for fun

but definitely cool

(very optional, work on something else if you have the time for this.)

### PR DESCRIPTION
**Pull request by HeeistHo**
can now sing the jeopardy theme and bohemian rhapsody when called properly

i had too much fun with this

closes #178

### CODE REVIEW

**Comment by HeeistHo** [comment]
oh i accidently made this branch off of another issue, oopsie

i believe its #145

**Review by WindowsVistaisCool — CHANGES_REQUESTED** [review]
absolutely not

**Review by WindowsVistaisCool — CHANGES_REQUESTED** [review]
ABSOLUTELY NOT

**Review by WindowsVistaisCool — APPROVED** [review]

**Review by MattD8957 — APPROVED** [review]
THIS IS AMAZING!!!!!

**Pull request merged**
